# Generated by Django 5.0.3 on 2026-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transporte', models.CharField(choices=[('propio', 'Vehículo propio (UPN)'), ('externo', 'Empresa externa')], default='propio', max_length=10, verbose_name='Tipo de transporte')),
                ('empresa_externa', models.CharField(blank=True, max_length=150, verbose_name='Empresa externa')),
                ('confirmado_en', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado en')),
            ],
            options={
                'verbose_name': 'Asignación de Transporte',
                'verbose_name_plural': 'Asignaciones de Transporte',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('tipo', models.CharField(choices=[('bus', 'Bus'), ('buseta', 'Buseta'), ('camioneta', 'Camioneta'), ('furgon', 'Furgón')], max_length=15, verbose_name='Tipo')),
                ('capacidad', models.PositiveSmallIntegerField(verbose_name='Capacidad (personas)')),
                ('estado_tecnico', models.CharField(choices=[('disponible', 'Disponible'), ('en_servicio', 'En Servicio'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20, verbose_name='Estado técnico')),
                ('foto_url', models.URLField(blank=True, verbose_name='Foto del vehículo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
            },
        ),
    ]
