# Generated by Django 5.0.3 on 2026-03-04 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salidas', '0002_initial'),
        ('transporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='conductor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_conductor', to=settings.AUTH_USER_MODEL, verbose_name='Conductor'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='salidas.salida', verbose_name='Salida'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='transporte.vehiculo', verbose_name='Vehículo'),
        ),
    ]
