# Generated by Django 6.0 on 2026-03-12 01:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_agregar_rendimiento_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='notas',
            field=models.TextField(blank=True, default='', verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_interno',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='N° Interno'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='propietario',
            field=models.CharField(choices=[('institucional', 'Institucional (UPN)'), ('externo', 'Flota Externa')], default='institucional', max_length=15, verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(choices=[('diesel', 'Diésel'), ('gasolina', 'Gasolina'), ('gas', 'Gas Natural')], default='diesel', max_length=10, verbose_name='Tipo de combustible'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='foto_url',
            field=models.URLField(blank=True, verbose_name='URL de foto externa'),
        ),
    ]
