# Generated by Django 6.0 on 2026-03-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_vehiculo_actualizado_en_vehiculo_anio_vehiculo_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('bus', 'Bus'), ('buseta', 'Buseta'), ('microbus', 'Microbús'), ('camioneta', 'Camioneta / Van'), ('furgon', 'Furgón')], max_length=15, verbose_name='Tipo'),
        ),
    ]
