# Generated by Django 5.0.3 on 2026-05-02 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaDirectorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('cargados', models.IntegerField(default=0)),
                ('duplicados', models.IntegerField(default=0)),
                ('errores', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('cargado_por', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Carga de Directorio',
                'db_table': 'estudiante_carga_directorio',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='EstudianteSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salida_id', models.IntegerField()),
                ('usuario_id', models.IntegerField()),
                ('foto_ficha', models.ImageField(blank=True, null=True, upload_to='inscripciones/fotos/')),
                ('firma_digital', models.ImageField(blank=True, null=True, upload_to='inscripciones/firmas/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('autorizado', 'Autorizado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscripción de Estudiante',
                'db_table': 'estudiante_salida_inscripcion',
                'unique_together': {('salida_id', 'usuario_id')},
            },
        ),
        migrations.CreateModel(
            name='DirectorioEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('facultad', models.CharField(blank=True, max_length=200)),
                ('programa', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='estudiante_infra.cargadirectorio')),
            ],
            options={
                'verbose_name': 'Directorio Estudiantil',
                'db_table': 'estudiante_directorio',
                'unique_together': {('carga', 'correo')},
            },
        ),
    ]
