# Generated by Django 5.0.3 on 2026-05-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante_infra', '0001_init_modulo_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('tipo_documento', models.CharField(choices=[('eps', 'Certificado EPS'), ('documento_identidad', 'Documento de Identidad')], max_length=50)),
                ('archivo', models.FileField(upload_to='estudiantes/documentos/')),
                ('fecha_subida', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento de Estudiante',
                'db_table': 'estudiante_documento',
                'unique_together': {('usuario_id', 'tipo_documento')},
            },
        ),
    ]
