# Generated by Django 5.0.3 on 2026-05-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante_infra', '0002_documentoestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorioestudiante',
            name='rol',
            field=models.CharField(default='estudiante', max_length=50),
        ),
    ]
