# Generated by Django 5.0.3 on 2026-05-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor_institucional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductorinstitucionalmodel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='conductores_institucionales/'),
        ),
    ]
