# Generated by Django 5.0.3 on 2026-05-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor_institucional', '0002_conductorinstitucionalmodel_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductorinstitucionalmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
