# Generated by Django 5.0.3 on 2026-03-25 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultadModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Facultad',
                'db_table': 'facultades',
            },
        ),
        migrations.CreateModel(
            name='ParametrosModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_galon', models.FloatField(default=0.0)),
                ('rendimiento_bus', models.FloatField(default=0.0)),
                ('rendimiento_buseta', models.FloatField(default=0.0)),
                ('rendimiento_camioneta', models.FloatField(default=0.0)),
                ('costo_noche', models.FloatField(default=0.0)),
                ('costo_hora_extra', models.FloatField(default=11000.0)),
                ('costo_hora_extra_2', models.FloatField(default=15000.0)),
                ('max_horas_viaje', models.FloatField(default=10.0)),
                ('horas_buffer', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name': 'Parámetros del Sistema',
                'db_table': 'parametros_sistema',
            },
        ),
        migrations.CreateModel(
            name='VentanaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_apertura', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ventana de Programación',
                'db_table': 'ventanas_programacion',
            },
        ),
        migrations.CreateModel(
            name='ProgramaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='parametros.facultadmodelo')),
            ],
            options={
                'verbose_name': 'Programa',
                'db_table': 'programas',
            },
        ),
    ]
