# Generated by Django 5.0.3 on 2026-03-25 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItinerarioModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salida_id', models.IntegerField(unique=True)),
                ('poligonal_mapa', models.TextField(default='{}')),
                ('distancia_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duracion_horas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Itinerario',
                'verbose_name_plural': 'Itinerarios',
                'db_table': 'salidas_itinerario_itinerario',
            },
        ),
        migrations.CreateModel(
            name='PuntoParadaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=1)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(default='trabajo_campo', max_length=50)),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='salidas_itinerario.itinerariomodelo')),
            ],
            options={
                'verbose_name': 'Punto de Parada',
                'verbose_name_plural': 'Puntos de Parada',
                'db_table': 'salidas_itinerario_punto_parada',
                'ordering': ['itinerario', 'orden'],
            },
        ),
    ]
