# Generated by Django 5.0.3 on 2026-04-15 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionConsejoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salida_id', models.IntegerField(unique=True)),
                ('concejal_id', models.IntegerField()),
                ('concepto_financiero', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('acta', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_acta', models.DateField(blank=True, null=True)),
                ('fecha_decision', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Decisión de Consejo',
                'verbose_name_plural': 'Decisiones de Consejo',
                'db_table': 'salidas_consejo_decision',
            },
        ),
    ]
