# Generated by Django 5.0.3 on 2026-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_galon', models.FloatField(default=16500, help_text='Pg — Precio en pesos colombianos por galón de gasolina', verbose_name='Precio del galón (COP)')),
                ('rendimiento', models.FloatField(default=8, help_text='R — Kilómetros por galón que rinde el vehículo', verbose_name='Rendimiento del vehículo (km/galón)')),
                ('costo_noche', models.FloatField(default=222000, help_text='C_noche — Costo de hospedaje por noche en pesos', verbose_name='Costo por noche (COP)')),
                ('costo_hora_extra', models.FloatField(default=11000, help_text='C_hora — Costo por hora extra del conductor en pesos', verbose_name='Costo hora extra (COP)')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Parámetros del Sistema',
                'verbose_name_plural': 'Parámetros del Sistema',
            },
        ),
    ]
