# Generated by Django 6.0 on 2026-03-10 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Activa?')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='VentanaProgramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha_apertura', models.DateField(verbose_name='Fecha de apertura')),
                ('fecha_cierre', models.DateField(verbose_name='Fecha de cierre')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Activa?')),
            ],
            options={
                'verbose_name': 'Ventana de Programación',
                'verbose_name_plural': 'Ventanas de Programación',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='parametros.facultad', verbose_name='Facultad')),
            ],
            options={
                'verbose_name': 'Programa Académico',
                'verbose_name_plural': 'Programas Académicos',
                'ordering': ['facultad__nombre', 'nombre'],
            },
        ),
    ]
