# Generated by Django 6.0 on 2026-03-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_facultad_ventanaprogramacion_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrossistema',
            name='rendimiento_bus',
            field=models.FloatField(default=5, help_text='Rendimiento típico: bus grande (35-50 pax)', verbose_name='🚌 Bus (km/gal)'),
        ),
        migrations.AddField(
            model_name='parametrossistema',
            name='rendimiento_buseta',
            field=models.FloatField(default=8, help_text='Rendimiento típico: buseta (15-25 pax)', verbose_name='🚐 Buseta (km/gal)'),
        ),
        migrations.AddField(
            model_name='parametrossistema',
            name='rendimiento_camioneta',
            field=models.FloatField(default=12, help_text='Rendimiento típico: camioneta (5-12 pax)', verbose_name='🛻 Camioneta (km/gal)'),
        ),
        migrations.AlterField(
            model_name='parametrossistema',
            name='rendimiento',
            field=models.FloatField(default=8, help_text='R — Fallback cuando no se especifica tipo de vehículo', verbose_name='Rendimiento genérico (km/galón)'),
        ),
    ]
