# Generated by Django 6.0 on 2026-03-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_rendimiento_por_tipo_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultad',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='codigo',
        ),
    ]
