# Generated by Django 6.0 on 2026-03-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0005_remove_facultad_codigo_remove_programa_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrossistema',
            name='costo_hora_extra_2',
            field=models.FloatField(default=15000, help_text='HE2 — Hora extra después de las 6:00 pm', verbose_name='Costo hora extra nocturna (COP)'),
        ),
        migrations.AlterField(
            model_name='parametrossistema',
            name='costo_hora_extra',
            field=models.FloatField(default=11000, help_text='HE1 — Hora extra entre 5:00 pm y 6:00 pm (máx 1/día)', verbose_name='Costo hora extra (COP)'),
        ),
        migrations.AlterField(
            model_name='parametrossistema',
            name='costo_noche',
            field=models.FloatField(default=222000, help_text='Vu — Valor del viático completo del conductor por día', verbose_name='Costo por noche (COP)'),
        ),
    ]
