# Generated by Django 6.0 on 2026-03-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0007_agregar_max_horas_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrossistema',
            name='horas_buffer',
            field=models.FloatField(default=1, help_text='Horas extra no calculadas (paradas, imprevistos). Se suman al tiempo de ruta.', verbose_name='Horas buffer sobre recorrido'),
        ),
    ]
