# Generated by Django 5.0.3 on 2026-03-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(default='bus', max_length=20)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('numero_interno', models.CharField(blank=True, max_length=20)),
                ('capacidad', models.PositiveIntegerField()),
                ('rendimiento_kmgal', models.FloatField(default=8.0)),
                ('tipo_combustible', models.CharField(default='diesel', max_length=20)),
                ('propietario', models.CharField(default='institucional', max_length=20)),
                ('estado_tecnico', models.CharField(default='disponible', max_length=20)),
                ('foto_url', models.URLField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'db_table': 'vehiculos',
            },
        ),
        migrations.CreateModel(
            name='AsignacionModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salida_id', models.PositiveIntegerField()),
                ('conductor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_transporte', models.CharField(default='propio', max_length=20)),
                ('empresa_externa', models.CharField(blank=True, max_length=200)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='transporte.vehiculomodelo')),
            ],
            options={
                'verbose_name': 'Asignación',
                'db_table': 'asignaciones',
            },
        ),
    ]
