# Generated by Django 5.0.3 on 2026-04-22 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica_empresa_transporte', '0001_empresas_conductores_externos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductorExternoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('licencia', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores', to='logistica_empresa_transporte.empresatransportemodel')),
            ],
            options={
                'verbose_name': 'Conductor Externo',
                'verbose_name_plural': 'Conductores Externos',
                'db_table': 'logistica_conductor_externo',
            },
        ),
    ]
