# Generated by Django 5.0.3 on 2026-05-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica_conductor_externo', '0001_empresas_conductores_externos'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductorexternomodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='conductorexternomodel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='conductores_externos/'),
        ),
    ]
