# Generated by Django 5.0.3 on 2026-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('mecanica', 'Mecánica'), ('seguridad', 'Seguridad'), ('documentos', 'Documentos'), ('confort', 'Confort')], max_length=15, verbose_name='Categoría')),
                ('item', models.CharField(max_length=200, verbose_name='Ítem a verificar')),
                ('estado', models.CharField(choices=[('ok', 'OK'), ('no_ok', 'No OK'), ('na', 'N/A'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('evidencia_url', models.URLField(blank=True, verbose_name='Evidencia fotográfica')),
            ],
            options={
                'verbose_name': 'Ítem de Checklist',
                'verbose_name_plural': 'Ítems de Checklist',
                'ordering': ['categoria', 'item'],
            },
        ),
    ]
