# Generated by Django 5.0.3 on 2026-03-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklist', '0001_initial'),
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchecklist',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_checklist', to='transporte.asignacion', verbose_name='Asignación'),
        ),
    ]
