# Generated by Django 5.0.3 on 2026-03-25 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultad_infra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas', to='facultad_infra.facultadmodel')),
            ],
            options={
                'db_table': 'programas',
            },
        ),
    ]
