# Generated by Django 5.0.3 on 2026-03-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventana_infra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventanamodel',
            name='periodo',
        ),
        migrations.AddField(
            model_name='ventanamodel',
            name='fecha_apertura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventanamodel',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
