# Generated by Django 6.0 on 2026-03-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='rendimiento_kmgal',
            field=models.FloatField(default=8, help_text='Kilómetros por galón de combustible', verbose_name='Rendimiento (km/galón)'),
        ),
    ]
