# Generated by Django 5.0.3 on 2026-03-25 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaneacionModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.TextField(blank=True)),
                ('relacion_syllabus', models.TextField(blank=True)),
                ('objetivo_general', models.TextField(blank=True)),
                ('estrategia_metodologica', models.TextField(blank=True)),
                ('productos_esperados', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalidaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('asignatura', models.CharField(max_length=200)),
                ('semestre', models.CharField(max_length=20)),
                ('facultad', models.CharField(max_length=200)),
                ('programa', models.CharField(max_length=200)),
                ('num_estudiantes', models.PositiveIntegerField(default=0)),
                ('justificacion', models.TextField(blank=True)),
                ('estado', models.CharField(default='borrador', max_length=30)),
                ('profesor_id', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('distancia_total_km', models.FloatField(default=0.0)),
                ('duracion_dias', models.FloatField(default=1.0)),
                ('horas_viaje', models.FloatField(default=9.0)),
                ('costo_estimado', models.FloatField(default=0.0)),
                ('icono', models.CharField(default='IcoMap', max_length=50)),
                ('color', models.CharField(default='#4A8DAC', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
                'db_table': 'salidas',
            },
        ),
        migrations.CreateModel(
            name='ObjetivoEspecificoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('planeacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='salidas.planeacionmodelo')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoRutaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=100)),
                ('tiempo_estimado', models.CharField(blank=True, max_length=50)),
                ('actividad', models.CharField(blank=True, max_length=200)),
                ('es_hospedaje', models.BooleanField(default=False)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('hora_programada', models.TimeField(blank=True, null=True)),
                ('notas_itinerario', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('es_retorno', models.BooleanField(default=False)),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_ruta_modelo', to='salidas.salidamodelo')),
            ],
        ),
        migrations.AddField(
            model_name='planeacionmodelo',
            name='salida',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_modelo', to='salidas.salidamodelo'),
        ),
        migrations.CreateModel(
            name='CriterioEvaluacionModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='salidas.salidamodelo')),
            ],
        ),
    ]
