# Generated by Django 5.0.3 on 2026-03-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('asignatura', models.CharField(max_length=200)),
                ('semestre', models.CharField(max_length=20)),
                ('facultad', models.CharField(max_length=200)),
                ('programa', models.CharField(max_length=200)),
                ('num_estudiantes', models.PositiveIntegerField(default=0)),
                ('justificacion', models.TextField(blank=True)),
                ('estado', models.CharField(default='borrador', max_length=30)),
                ('profesor_id', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('distancia_total_km', models.FloatField(default=0.0)),
                ('duracion_dias', models.FloatField(default=1.0)),
                ('horas_viaje', models.FloatField(default=9.0)),
                ('costo_estimado', models.FloatField(default=0.0)),
                ('icono', models.CharField(default='IcoMap', max_length=50)),
                ('color', models.CharField(default='#4A8DAC', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
                'db_table': 'salidas',
            },
        ),
    ]
