# Generated by Django 5.0.3 on 2026-03-24 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioEvaluacionModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='salidas.salidamodelo')),
            ],
        ),
        migrations.CreateModel(
            name='PlaneacionModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.TextField(blank=True)),
                ('relacion_syllabus', models.TextField(blank=True)),
                ('objetivo_general', models.TextField(blank=True)),
                ('estrategia_metodologica', models.TextField(blank=True)),
                ('productos_esperados', models.TextField(blank=True)),
                ('salida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planeacion_modelo', to='salidas.salidamodelo')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoEspecificoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('planeacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='salidas.planeacionmodelo')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoRutaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=100)),
                ('tiempo_estimado', models.CharField(blank=True, max_length=50)),
                ('actividad', models.CharField(blank=True, max_length=200)),
                ('es_hospedaje', models.BooleanField(default=False)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('hora_programada', models.TimeField(blank=True, null=True)),
                ('notas_itinerario', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('es_retorno', models.BooleanField(default=False)),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_ruta_modelo', to='salidas.salidamodelo')),
            ],
        ),
    ]
