# Generated by Django 5.0.3 on 2026-03-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParadaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerario_id', models.IntegerField(help_text='ID del itinerario principal de la Salida')),
                ('orden', models.IntegerField(default=1)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(default='trabajo_campo', max_length=50)),
            ],
            options={
                'verbose_name': 'Parada del Itinerario',
                'verbose_name_plural': 'Paradas del Itinerario',
                'db_table': 'salidas_itinerario_parada',
            },
        ),
    ]
