# Generated by Django 5.0.3 on 2026-03-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paradamodelo',
            name='actividad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paradamodelo',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paradamodelo',
            name='fecha_programada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paradamodelo',
            name='hora_programada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paradamodelo',
            name='icono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paradamodelo',
            name='notas_itinerario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paradamodelo',
            name='tiempo_estimado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
