# Generated by Django 5.0.3 on 2026-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abordaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='6 caracteres alfanuméricos generados al activar el código', max_length=6, verbose_name='Código de verificación')),
                ('codigo_expira_en', models.DateTimeField(blank=True, null=True, verbose_name='Código expira en')),
                ('abordado', models.BooleanField(default=False, verbose_name='¿Ya abordó?')),
                ('verificado_en', models.DateTimeField(blank=True, null=True, verbose_name='Verificado en')),
                ('foto_url', models.URLField(blank=True, verbose_name='Foto del abordaje')),
            ],
            options={
                'verbose_name': 'Registro de Abordaje',
                'verbose_name_plural': 'Registros de Abordaje',
            },
        ),
        migrations.CreateModel(
            name='DocumentoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('identidad', 'Documento de Identidad'), ('eps_arl', 'EPS / ARL'), ('consentimiento', 'Consentimiento Informado'), ('poliza', 'Póliza de Seguro')], max_length=20, verbose_name='Tipo de documento')),
                ('archivo_url', models.URLField(blank=True, verbose_name='Archivo')),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido'), ('no_cargado', 'No cargado')], default='no_cargado', max_length=15)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Vence el')),
            ],
            options={
                'verbose_name': 'Documento del Estudiante',
                'verbose_name_plural': 'Documentos del Estudiante',
            },
        ),
    ]
