# Generated by Django 5.0.3 on 2026-03-04 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abordaje', '0001_initial'),
        ('salidas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abordaje',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_abordajes', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='abordaje',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_abordaje', to='salidas.salida', verbose_name='Salida'),
        ),
        migrations.AddField(
            model_name='abordaje',
            name='verificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.AddField(
            model_name='documentoestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_documentos', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='abordaje',
            unique_together={('salida', 'estudiante')},
        ),
        migrations.AlterUniqueTogether(
            name='documentoestudiante',
            unique_together={('estudiante', 'tipo')},
        ),
    ]
