# Generated by Django 5.0.3 on 2026-04-17 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programa_infra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='programa_infra.programamodel')),
            ],
            options={
                'db_table': 'materias',
            },
        ),
    ]
