# Generated by Django 5.0.3 on 2026-03-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='color',
            field=models.CharField(blank=True, default='#4A8DAC', max_length=50, verbose_name='Color UI'),
        ),
        migrations.AddField(
            model_name='salida',
            name='icono',
            field=models.CharField(blank=True, default='IcoMap', max_length=50, verbose_name='Icono UI'),
        ),
    ]
