# Generated by Django 6.0 on 2026-03-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0007_salida_grupal'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoruta',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección completa'),
        ),
        migrations.AddField(
            model_name='puntoruta',
            name='es_hospedaje',
            field=models.BooleanField(default=False, verbose_name='¿Es parada de hospedaje?'),
        ),
        migrations.AddField(
            model_name='puntoruta',
            name='latitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='puntoruta',
            name='longitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='puntoruta',
            name='motivo',
            field=models.CharField(blank=True, choices=[('almuerzo', 'Almuerzo'), ('refrigerio', 'Refrigerio'), ('bano', 'Baño'), ('actividad_academica', 'Actividad Académica'), ('recoger_pasajero', 'Recoger Pasajero'), ('hospedaje', 'Hospedaje / Pernoctar'), ('descanso_nocturno', 'Descanso Nocturno'), ('otro', 'Otro')], max_length=30, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='puntoruta',
            name='tiempo_estimado',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tiempo estimado'),
        ),
    ]
