# Generated by Django 6.0 on 2026-03-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0010_puntoruta_color_puntoruta_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoruta',
            name='es_retorno',
            field=models.BooleanField(default=False, verbose_name='¿Es parada del retorno?'),
        ),
    ]
