# Generated by Django 6.0 on 2026-03-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0012_agregar_campos_costo_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='tipo_vehiculo_calculo',
            field=models.CharField(blank=True, default='bus', help_text='bus, buseta o camioneta — determina el rendimiento', max_length=15, verbose_name='Tipo de vehículo (para cálculo)'),
        ),
    ]
