# Generated by Django 5.0.3 on 2026-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Competencia',
            },
        ),
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('porcentaje', models.FloatField(default=0)),
                ('tipo', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Criterio de Evaluación',
            },
        ),
        migrations.CreateModel(
            name='CriterioRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=200, verbose_name='Criterio')),
                ('cumple', models.BooleanField(default=False, verbose_name='¿Cumple?')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
            ],
            options={
                'verbose_name': 'Criterio de Revisión',
            },
        ),
        migrations.CreateModel(
            name='DecisionConsejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('aprobada', 'Aprobada'), ('solicitar_cambios', 'Solicitar Cambios'), ('rechazada', 'Rechazada')], max_length=25, verbose_name='Decisión')),
                ('tiempo_ajuste_dias', models.PositiveSmallIntegerField(default=0, help_text='Solo aplica si la decisión es solicitar_cambios', verbose_name='Días para ajuste')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Decisión del Consejo',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Objetivo Específico',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PlaneacionPedagogica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_general', models.TextField(blank=True, verbose_name='Objetivo general')),
                ('metodologia', models.TextField(blank=True, verbose_name='Metodología')),
            ],
            options={
                'verbose_name': 'Planeación Pedagógica',
            },
        ),
        migrations.CreateModel(
            name='PuntoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('nombre', models.CharField(max_length=200)),
                ('hora_estimada', models.TimeField(blank=True, null=True)),
                ('actividad', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('origen', 'Origen'), ('parada', 'Parada'), ('destino', 'Destino')], default='parada', max_length=10)),
            ],
            options={
                'verbose_name': 'Punto de Ruta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(blank=True, choices=[('favorable', 'Favorable'), ('favorable_con_ajustes', 'Favorable con Ajustes'), ('no_favorable', 'No Favorable')], max_length=30, verbose_name='Concepto')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Revisión de Coordinador',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la salida')),
                ('asignatura', models.CharField(blank=True, max_length=150, verbose_name='Asignatura')),
                ('semestre', models.CharField(blank=True, max_length=10, verbose_name='Semestre')),
                ('programa', models.CharField(blank=True, max_length=150, verbose_name='Programa académico')),
                ('num_estudiantes', models.PositiveIntegerField(default=0, verbose_name='N° estudiantes')),
                ('justificacion', models.TextField(blank=True, verbose_name='Justificación')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('en_revision', 'En Revisión'), ('favorable', 'Favorable'), ('pendiente_ajuste', 'Pendiente de Ajuste'), ('ajustada', 'Ajustada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('en_preparacion', 'En Preparación'), ('en_ejecucion', 'En Ejecución'), ('finalizada', 'Finalizada'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='borrador', max_length=25, verbose_name='Estado')),
                ('tipo_transporte', models.CharField(blank=True, max_length=20, verbose_name='Tipo de transporte')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salida de Campo',
                'verbose_name_plural': 'Salidas de Campo',
                'ordering': ['-created_at'],
            },
        ),
    ]
