# Generated by Django 5.0.3 on 2026-03-04 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salidas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionconsejo',
            name='decidido_por',
            field=models.ForeignKey(limit_choices_to={'rol': 'consejo'}, on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_emitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objetivoespecifico',
            name='planeacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='salidas.planeacionpedagogica'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='planeacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='salidas.planeacionpedagogica'),
        ),
        migrations.AddField(
            model_name='revision',
            name='coordinador',
            field=models.ForeignKey(limit_choices_to={'rol': 'coordinador_academico'}, on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_emitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='criteriorevision',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='salidas.revision'),
        ),
        migrations.AddField(
            model_name='salida',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.PROTECT, related_name='mis_salidas', to=settings.AUTH_USER_MODEL, verbose_name='Profesor'),
        ),
        migrations.AddField(
            model_name='revision',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='salidas.salida'),
        ),
        migrations.AddField(
            model_name='puntoruta',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_ruta', to='salidas.salida'),
        ),
        migrations.AddField(
            model_name='planeacionpedagogica',
            name='salida',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planeacion', to='salidas.salida'),
        ),
        migrations.AddField(
            model_name='decisionconsejo',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones', to='salidas.salida'),
        ),
        migrations.AddField(
            model_name='criterioevaluacion',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios_evaluacion', to='salidas.salida'),
        ),
    ]
