# Generated by Django 5.0.3 on 2026-03-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0003_salida_color_salida_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='resumen',
            field=models.CharField(blank=True, max_length=255, verbose_name='Resumen (texto tarjeta)'),
        ),
    ]
