# Generated by Django 5.0.3 on 2026-03-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0004_salida_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='facultad',
            field=models.CharField(blank=True, max_length=150, verbose_name='Facultad'),
        ),
    ]
