# Generated by Django 5.0.3 on 2026-03-05 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0005_salida_facultad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='productos_esperados',
            field=models.TextField(blank=True, verbose_name='Productos esperados'),
        ),
        migrations.AddField(
            model_name='salida',
            name='relacion_syllabus',
            field=models.TextField(blank=True, verbose_name='Relación con syllabus'),
        ),
        migrations.AlterField(
            model_name='criterioevaluacion',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='criterioevaluacion',
            name='porcentaje',
            field=models.FloatField(default=0, verbose_name='Porcentaje (%)'),
        ),
        migrations.AlterField(
            model_name='criterioevaluacion',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de criterio'),
        ),
        migrations.AlterField(
            model_name='decisionconsejo',
            name='decidido_por',
            field=models.ForeignKey(limit_choices_to={'rol': 'consejo'}, on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Decidido por'),
        ),
        migrations.AlterField(
            model_name='puntoruta',
            name='actividad',
            field=models.TextField(blank=True, verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='puntoruta',
            name='hora_estimada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora estimada'),
        ),
        migrations.AlterField(
            model_name='puntoruta',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del punto'),
        ),
        migrations.AlterField(
            model_name='puntoruta',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='puntoruta',
            name='tipo',
            field=models.CharField(choices=[('origen', 'Origen'), ('parada', 'Parada'), ('destino', 'Destino')], default='parada', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='coordinador',
            field=models.ForeignKey(limit_choices_to={'rol': 'coordinador_academico'}, on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador'),
        ),
    ]
