# Generated by Django 6.0 on 2026-03-06 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0006_salida_productos_esperados_salida_relacion_syllabus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='es_grupal',
            field=models.BooleanField(default=False, verbose_name='¿Salida grupal?'),
        ),
        migrations.AddField(
            model_name='salida',
            name='profesores_asociados',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'profesor'}, related_name='salidas_asociadas', to=settings.AUTH_USER_MODEL, verbose_name='Profesores asociados'),
        ),
    ]
