# Generated by Django 6.0 on 2026-03-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0008_add_coords_motivo_hospedaje_to_puntoruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoruta',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha programada'),
        ),
        migrations.AddField(
            model_name='puntoruta',
            name='hora_programada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora programada'),
        ),
        migrations.AddField(
            model_name='puntoruta',
            name='notas_itinerario',
            field=models.CharField(blank=True, max_length=300, verbose_name='Notas del itinerario'),
        ),
    ]
