# Generated by Django 6.0 on 2026-03-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0009_add_itinerary_scheduling_to_puntoruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoruta',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Color Tema'),
        ),
        migrations.AddField(
            model_name='puntoruta',
            name='icono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono / Ilustración'),
        ),
    ]
