# Generated by Django 6.0 on 2026-03-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0011_add_es_retorno_to_punto_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='costo_estimado',
            field=models.FloatField(default=0, verbose_name='Costo estimado (COP)'),
        ),
        migrations.AddField(
            model_name='salida',
            name='distancia_total_km',
            field=models.FloatField(default=0, verbose_name='Distancia total (km)'),
        ),
        migrations.AddField(
            model_name='salida',
            name='duracion_dias',
            field=models.FloatField(default=1, verbose_name='Duración (días)'),
        ),
        migrations.AddField(
            model_name='salida',
            name='horas_viaje',
            field=models.FloatField(default=9, verbose_name='Horas totales de viaje'),
        ),
    ]
