# Generated by Django 5.0.3 on 2026-04-10 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionPedagogicaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salida_id', models.IntegerField(unique=True)),
                ('coordinador_id', models.IntegerField()),
                ('pertinencia_estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('pertinencia_obs', models.TextField(blank=True, null=True)),
                ('objetivos_estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('objetivos_obs', models.TextField(blank=True, null=True)),
                ('metodologia_estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('metodologia_obs', models.TextField(blank=True, null=True)),
                ('viabilidad_estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('viabilidad_obs', models.TextField(blank=True, null=True)),
                ('concepto_final', models.CharField(default='PENDIENTE', max_length=50)),
                ('fecha_revision', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Revisión Pedagógica',
                'verbose_name_plural': 'Revisiones Pedagógicas',
                'db_table': 'salidas_coordinacion_revision',
            },
        ),
    ]
