# Generated by Django 5.0.3 on 2026-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mecanica', 'Mecánica'), ('accidente', 'Accidente'), ('clima', 'Clima'), ('vial', 'Vial'), ('salud', 'Salud'), ('otro', 'Otro')], max_length=15, verbose_name='Tipo de novedad')),
                ('urgencia', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10, verbose_name='Urgencia')),
                ('descripcion', models.TextField(verbose_name='Descripción del incidente')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('resuelta', 'Resuelta')], default='abierta', max_length=10, verbose_name='Estado')),
                ('latitud', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitud', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('registrado_en', models.DateTimeField(auto_now_add=True, verbose_name='Registrado en')),
                ('resuelto_en', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto en')),
            ],
            options={
                'verbose_name': 'Novedad del Viaje',
                'verbose_name_plural': 'Novedades del Viaje',
                'ordering': ['-registrado_en'],
            },
        ),
    ]
