# Generated by Django 5.0.3 on 2026-03-04 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novedades', '0001_initial'),
        ('salidas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='reportado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por'),
        ),
        migrations.AddField(
            model_name='novedad',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='salidas.salida', verbose_name='Salida'),
        ),
    ]
