# Generated by Django 5.0.3 on 2026-03-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaneacionModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salida_id', models.IntegerField()),
                ('competencias', models.TextField(blank=True, null=True)),
                ('resultados', models.TextField(blank=True, null=True)),
                ('guion', models.TextField(blank=True, null=True)),
                ('requiere_guia', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Planeacion Pedagogica',
                'verbose_name_plural': 'Planeaciones Pedagogicas',
                'db_table': 'salidas_planeacion_planeacion',
            },
        ),
    ]
