# Generated by Django 5.0.3 on 2026-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('combustible', 'Combustible'), ('hospedaje', 'Hospedaje'), ('alimentacion', 'Alimentación'), ('entrada', 'Entradas'), ('otro', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('monto', models.FloatField(verbose_name='Monto (COP)')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gasto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_asignado', models.FloatField(default=0, verbose_name='Total asignado (COP)')),
                ('ejecutado', models.FloatField(default=0, verbose_name='Total ejecutado (COP)')),
            ],
            options={
                'verbose_name': 'Presupuesto',
            },
        ),
    ]
