# Generated by Django 5.0.3 on 2026-05-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_infra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='rol',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('conductor', 'Conductor'), ('profesor', 'Profesor'), ('admin', 'Administrador')], default='estudiante', max_length=50),
        ),
    ]
