# Generated by Django 5.0.3 on 2026-05-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_infra', '0002_usuariomodel_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuariomodel',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
