# Generated by Django 5.0.3 on 2026-05-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_infra', '0003_usuariomodel_cedula_usuariomodel_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True),
        ),
    ]
