# Generated by Django 5.0.3 on 2026-03-25 19:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('numero_interno', models.CharField(blank=True, max_length=50, null=True)),
                ('capacidad', models.IntegerField()),
                ('rendimiento_kmgal', models.FloatField()),
                ('tipo_combustible', models.CharField(max_length=50)),
                ('propietario', models.CharField(max_length=50)),
                ('estado_tecnico', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('foto_url', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
            ],
            options={
                'db_table': 'logistica_vehiculo',
            },
        ),
    ]
