# Generated by Django 5.0.3 on 2026-03-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'facultades',
            },
        ),
    ]
