# Generated by Django 5.0.3 on 2026-03-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('asignatura', models.CharField(blank=True, max_length=200, null=True)),
                ('semestre', models.CharField(blank=True, max_length=20, null=True)),
                ('facultad_id', models.IntegerField(blank=True, null=True)),
                ('programa_id', models.IntegerField(blank=True, null=True)),
                ('num_estudiantes', models.IntegerField(default=0)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='BORRADOR', max_length=50)),
                ('profesor_id', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('distancia_total_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duracion_dias', models.DecimalField(decimal_places=1, default=1.0, max_digits=5)),
                ('horas_viaje', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Salida Core',
                'verbose_name_plural': 'Salidas Core',
                'db_table': 'salidas_core_salida',
            },
        ),
    ]
