# Generated by Django 5.0.3 on 2026-03-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaVehiculoAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salida_id', models.IntegerField()),
                ('vehiculo_id', models.UUIDField()),
            ],
            options={
                'db_table': 'salidas_core_salida_vehiculo',
                'unique_together': {('salida_id', 'vehiculo_id')},
            },
        ),
    ]
