# Generated by Django 5.0.3 on 2026-04-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas_core', '0002_salidavehiculoasignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidamodelo',
            name='color',
            field=models.CharField(default='#16a34a', max_length=50),
        ),
        migrations.AddField(
            model_name='salidamodelo',
            name='icono',
            field=models.CharField(default='IcoMountain', max_length=50),
        ),
    ]
