# Generated by Django 5.0.3 on 2026-04-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas_core', '0004_campos_pasos_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidamodelo',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
