# Generated by Django 5.0.3 on 2026-04-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas_core', '0005_salidamodelo_hora_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionExternaLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salida_id', models.IntegerField(unique=True)),
                ('empresa', models.CharField(max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('costo_proyectado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Asignación Externa',
                'db_table': 'salidas_logistica_asignacion_externa',
            },
        ),
        migrations.CreateModel(
            name='CierreOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salida_id', models.IntegerField(unique=True)),
                ('km_final', models.IntegerField()),
                ('checklist_limpieza', models.BooleanField(default=False)),
                ('checklist_llantas', models.BooleanField(default=False)),
                ('checklist_luces', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cierre Operativo',
                'db_table': 'salidas_logistica_cierres',
            },
        ),
        migrations.CreateModel(
            name='NovedadOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salida_id', models.IntegerField()),
                ('nivel', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Novedad Operativa',
                'db_table': 'salidas_logistica_novedades',
            },
        ),
    ]
