# Generated by Django 5.0.3 on 2026-04-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas_core', '0006_empresas_conductores_externos'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionexternalogistica',
            name='capacidad_asignada',
            field=models.IntegerField(default=0),
        ),
    ]
