# Generated by Django 5.0.3 on 2026-05-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas_core', '0007_asignacionexternalogistica_capacidad_asignada'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidamodelo',
            name='nota_cambio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
