# Generated by Django 5.0.3 on 2026-05-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas_core', '0008_salidamodelo_nota_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidamodelo',
            name='pin_acceso',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
