# Generated by Django 5.0.3 on 2026-05-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas_core', '0009_salidamodelo_pin_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedadoperativa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='novedades/'),
        ),
    ]
