# Generated by Django 5.0.3 on 2026-05-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas_core', '0010_novedadoperativa_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salida_id', models.IntegerField()),
                ('parada_id', models.IntegerField()),
                ('parada_nombre', models.CharField(max_length=300)),
                ('reportado_por', models.CharField(default='conductor', max_length=20)),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Checkpoint de Parada',
                'db_table': 'salidas_checkpoint_parada',
                'unique_together': {('salida_id', 'parada_id', 'reportado_por')},
            },
        ),
    ]
