# Generated by Django 6.0 on 2026-03-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0006_agregar_costo_hora_extra_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrossistema',
            name='max_horas_viaje',
            field=models.FloatField(default=10, help_text='Límite máximo de horas de conducción por día', verbose_name='Máximo horas de viaje/día'),
        ),
    ]
